### PR TITLE
Eslint

### PR DESCRIPTION
**Pull request by jtheletter6**
Setup and ran eslint fix on all js/jsx files in client and server

### CODE REVIEW

**Review by PRamos1196 — APPROVED** [review]
Looks good

**Review by stevegardiner26 — CHANGES_REQUESTED** [review]
```
 
       Creating an optimized production build...
/tmp/build_a8fc2117_/client/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^
Error: Failed to load config "airbnb" to extend from.
Referenced from: /tmp/build_a8fc2117_/client/.eslintrc.js
    at configMissingError (/tmp/build_a8fc2117_/client/node_modules/@eslint/eslintrc/lib/config-array-factory.js:289:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/tmp/build_a8fc2117_/client/node_modules/@eslint/eslintrc/lib/config-array-factory.js:877:23)
    at ConfigArrayFactory._loadExtends (/tmp/build_a8fc2117_/client/node_modules/@eslint/eslintrc/lib/config-array-factory.js:780:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/tmp/build_a8fc2117_/client/node_modules/@eslint/eslintrc/lib/config-array-factory.js:719:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/tmp/build_a8fc2117_/client/node_modules/@eslint/eslintrc/lib/config-array-factory.js:664:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/tmp/build_a8fc2117_/client/node_modules/@eslint/eslintrc/lib/config-array-factory.js:510:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/tmp/build_a8fc2117_/client/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:378:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/tmp/build_a8fc2117_/client/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:397:20)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/tmp/build_a8fc2117_/client/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:18)
    at FileEnumerator._iterateFilesWithFile (/tmp/build_a8fc2117_/client/node_modules/eslint/lib/cli-engine/file-enumerator.js:365:43)
    at FileEnumerator._iterateFiles (/tmp/build_a8fc2117_/client/node_modules/eslint/lib/cli-engine/file-enumerator.js:346:25)
    at FileEnumerator.iterateFiles (/tmp/build_a8fc2117_/client/node_modules/eslint/lib/cli-engine/file-enumerator.js:296:59)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (/tmp/build_a8fc2117_/client/node_modules/eslint/lib/cli-engine/cli-engine.js:770:48) {
  messageTemplate: 'extend-config-missing',
  messageData: {
    configName: 'airbnb',
    importerName: '/tmp/build_a8fc2117_/client/.eslintrc.js'
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the client@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.z0xV9/_logs/2020-11-06T03_15_50_919Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project3-famble@1.0.0 heroku-postbuild: `NPM_CONFIG_PRODUCTION=false npm install --prefix client && npm run build --prefix client`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project3-famble@1.0.0 heroku-postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.z0xV9/_logs/2020-11-06T03_15_50_940Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```
- I doubled checked pushing to heroku and got this build error. We prob wanna fix this first
- Also I think we should have a discussion about the .js files vs the .jsx files cause we if it doesn't detect auto-restart

**Comment by jtheletter6** [comment]
I have seen this error before and the airbnb eslint was not in the package.json. Let me fix that for this branch. I got the jsx working to detect the change and restart

**Comment by jtheletter6** [comment]
Just built and deployed to Heroku to test and it built successfully. The page still does not load bc it does not have your latest fix for deploying to heroku.

**Review by stevegardiner26 — APPROVED** [review]

**Pull request merged**
