### PR TITLE
Login

### PR DESCRIPTION
**Pull request by jtheletter6**
Added general login flow as well as file structure for different pages. Created routes for those pages using React router. Also commented the redirects from the homepage which will be updated once I know the logic to use. A redirect was successfully established from the login page to the dashboard page after oauth login success. Also added the ability for nodemon to track changes to jsx files. Pull request now because the structure will be useful for people to work on the other components. PLEASE MERGE BRANCH ESLINT BEFORE THIS. I checked out from the Eslint branch.

### CODE REVIEW

**Review by VivekSreenivasan — APPROVED** [review]
Linted well and looks good overall

**Review by stevegardiner26 — APPROVED** [review]
Approved, but I have two tiny nit picks that we might want to discuss:
1. We should have the file names of components start with a capital letter so `login.jsx` is `Login.jsx` I think that is proper react format.
2. We have all the react components in a lot of different files. It might make sense to have a `pages` folder and a `components` folder. And just put pages/components in the respective folder. We can also have subfolders in the components folder.
Works in Heroku!!!!

**Comment by jtheletter6** [comment]
> Approved, but I have two tiny nit picks that we might want to discuss:
> 
> 1. We should have the file names of components start with a capital letter so `login.jsx` is `Login.jsx` I think that is proper react format.
> 2. We have all the react components in a lot of different files. It might make sense to have a `pages` folder and a `components` folder. And just put pages/components in the respective folder. We can also have subfolders in the components folder.
>    Works in Heroku!!!!

Yes I am okay with changing the names that way, I normally do it that but I was not sure whether we'd want that. The reason I put them in separate folder is because when we add dedicated styling and subcomponents, they can all stay within that page's folder. I anticipate that we will have different people working on different pages, so that's why I did that. But if you feel like that doesn't make sense, then feel free to put them all in the same folder. 

@stevegardiner26

**Review by PRamos1196 — APPROVED** [review]
Looks good

**Pull request merged**
