### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by VivekSreenivasan**
Added the dashboard table that displays games and such
I used material UI for the table

### CODE REVIEW

**Review by jtheletter6 — CHANGES_REQUESTED** [review]
Something is breaking the heroku deployment for the dashboard page. Please see attached. You can also check https://famble.herokuapp.com/dashboard
image

**Comment by VivekSreenivasan** [comment]
I ran it again locally to see if I missed something and it worked fine.  I'll look further into it.

**Comment by VivekSreenivasan** [comment]
Problem fixed
Had to add the material ui package to the package.json within client

**Review by jtheletter6 — APPROVED** [review]

**Review by stevegardiner26 — APPROVED** [review]
Solid AF!

**Review by PRamos1196 — APPROVED** [review]
Looks good

**Review by PRamos1196 — APPROVED** [review]
Looks good

**Comment by VivekSreenivasan** [comment]
Pull request #10 should be merged in first

**Pull request merged**
